import 'package:e_commerce_app/models/product.dart';

class myproducts {
  static List<Product> allproducts = [
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 899,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/images.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom1.jpeg',
      quantity: 1,
    ),
    Product(
        id: 1,
        name: 'Tv',
        category: 'Tv',
        price: 35000,
        description: 'stylish laptops',
        image: 'assets/electronics/tv.jpeg',
        quantity: 1),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom2.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom3.jpeg',
      quantity: 1,
    ),
    Product(
        id: 1,
        name: 'Washing maching',
        category: 'LG',
        price: 50000,
        description: 'stylish laptops',
        image: 'assets/electronics/wash.jpeg',
        quantity: 1),
    Product(
      id: 1,
      name: 'crop top',
      category: ' Stylish top',
      price: 899,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom2.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 1000,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/images1.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 2000,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/jackets.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 1500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/jackets2.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 2300,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/jackets1.jpeg',
      quantity: 1,
    ),
  ];
  static List<Product> menslist = [
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 899,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/images.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 1000,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/images1.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 2000,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/jackets.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 1500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/jackets2.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'mens shirts',
      category: ' Stylish Executive shirts',
      price: 2300,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/mens/jackets1.jpeg',
      quantity: 1,
    ),
  ];
  static List<Product> womenslist = [
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom1.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom1.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom2.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom3.jpeg',
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'womens crop tops',
      category: ' Stylish tops',
      price: 500,
      description: 'Men Blue Custom Fit Stretch End-on-End Shirt',
      image: 'assets/womens/wom4.jpeg',
      quantity: 1,
    ),
  ];
  static List<Product> electronics = [
    Product(
        id: 1,
        name: 'Tv',
        category: 'Tv',
        price: 35000,
        description: 'stylish laptops',
        image: 'assets/electronics/tv.jpeg',
        quantity: 1),
    Product(
        id: 1,
        name: 'Washing maching',
        category: 'LG',
        price: 50000,
        description: 'powerfull new model washing machine',
        image: 'assets/electronics/wash.jpeg',
        quantity: 1),
    Product(
        id: 1,
        name: 'LapTop',
        category: "Hp",
        price: 44000,
        description: 'new model thin laptop',
        image: 'assets/electronics/lap.jpeg',
        quantity: 1)
  ];
}
